[workspace]
members = [
    "lumina",
    "lumina-parser",
    "lumina-util",
    "lumina-key",
    "lumina-compiler",
    "lumina-typesystem",
]
exclude = [
  # Compiled separately with different flags as a staticlib
  "lumina-gc"
]
resolver = "2"
