name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pulling changes
        working-directory: workdir/
        run: |
          if [ -d "lumina/" ]; then
            cd lumina/
            git pull
          else
            git clone ${{ github.repository }} lumina
            echo "target" >> lumina/.gitignore
            echo "mdbook/publish" >> lumina/.gitignore
          fi

      - name: Build Documentation
        working-directory: workdir/lumina/mdbook
        run: |
          mdbook build -d publish/

      - name: Test
        working-directory: workdir/lumina
        run: |
          cargo test -- --nocapture
